//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Administrator.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Administrator {
	public Object uname;
	public Object password;
	public void login() {
	
	}
	
	public void manageAccounts() {
	
	}
	
	public void ManageQuestions() {
	
	}
	
	public void ViewProfile() {
	
	}
}
