//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Billing System.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Billing System {
	public Object billno;
	public Object date;
	public Object candidateid;
	public void payment() {
	
	}
}
