//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Candidate.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Candidate {
	public Object name;
	public Object login id;
	public Object passwod;
	public void login() {
	
	}
	
	public void selectTest() {
	
	}
	
	public void ViewProfile() {
	
	}
}
