//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Guest.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Guest {
	public Object name;
	public Object dob;
	public Object gender;
	public Object address;
	public void signUp() {
	
	}
	
	public void payment() {
	
	}
}
