//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Online Examination System.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Online Examination System {
	public void registration() {
	
	}
	
	public void validateUsers() {
	
	}
	
	public void conductTests() {
	
	}
}
