//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Teachers.java
//  @ Date : 9/29/2016
//  @ Author : 
//
//




public class Teachers {
	public Object uname;
	public Object password;
	public void login() {
	
	}
	
	public void contributQuestions() {
	
	}
	
	public void ViewProfile() {
	
	}
}
